// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createNoOpSupabaseQuery() {
  const proxyTarget = {} as Record<string, unknown>;
  let proxy: any;

  function createResult() {
    const result = {
      then(onFulfilled: (value: unknown) => unknown) {
        onFulfilled({ data: [], error: null });
        return result;
      },
      catch() {
        return result;
      },
    };
    return result;
  }

  const handler: ProxyHandler<typeof proxyTarget> = {
    get(_, prop) {
      if (prop === "upload") {
        return async () => ({ data: null, error: null });
      }
      if (prop === "getPublicUrl") {
        return () => ({ data: { publicUrl: "" }, error: null });
      }
      if (prop === "then") {
        return (onFulfilled: (value: unknown) => unknown) => {
          onFulfilled({ data: [], error: null });
          return proxy;
        };
      }
      if (prop === "catch") {
        return () => proxy;
      }
      if (typeof prop === "string" && ["select", "insert", "update", "delete", "maybeSingle", "single"].includes(prop)) {
        return () => createResult();
      }
      if (typeof prop === "string" && ["eq", "order", "limit", "range", "upsert"].includes(prop)) {
        return () => proxy;
      }
      return () => proxy;
    },
  };

  proxy = new Proxy(proxyTarget, handler);
  return proxy;
}

function createNoOpSupabaseClient() {
  const noOpAuth = {
    onAuthStateChange(callback: (event: string, session: unknown) => void) {
      const subscription = { unsubscribe: () => {} };
      setTimeout(() => callback("SIGNED_OUT", { session: null, user: null }), 0);
      return { data: { subscription }, error: null };
    },
    getSession: async () => ({ data: { session: null }, error: null }),
  };

  return {
    auth: noOpAuth,
    from: () => createNoOpSupabaseQuery(),
  } as unknown as ReturnType<typeof createClient>;
}

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    if (typeof window !== "undefined") {
      console.warn(
        "[Supabase] Missing VITE_SUPABASE_URL/VITE_SUPABASE_PUBLISHABLE_KEY in the browser. Using no-op fallback.",
      );
      return createNoOpSupabaseClient();
    }

    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
